### ISSUE TITLE
No Documentation

### ISSUE THREAD

**Issue by ChilliByte** [isaacrg/open-cms#12]
It'd be great if I new what any of the code did, and how I could modify/install/use/whatever your CMS.

**Comment by ChilliByte** [comment]
yes this is a meaningless issue to get your attention.

**Comment by isaacrg** [comment]
@ChilliByte Hi! I will add some docs very soon. PS, I edited your comment, to add some exclamation marks.

**Comment by ChilliByte** [comment]
:D :+1:
